<!-- <h1>Registrate</h1>

<form action="#" method="post">
    <div>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre">
    </div>
    <div>
        <label for="email">email</label>
        <input type="text" name="email" id="email">
    </div>
    <div>
        <label for="contrasena">Contraseña</label>
        <input type="password" name="contrasena" id="contrasena">
    </div>

    <div>
        <input type="submit" value="Enviar">
    </div>
</form> -->
<?= $data["form"];?>
<a href="./login">Login</a>